### ISSUE TITLE
How to customize the InputButtonComponent Prop. 

### ISSUE THREAD

**Issue by SupaMario123** [mgcrea/react-native-propel-kit#2]
Hello, 

first thank you for providing such a great package.
I think this is not a real Issue but if you have time it would be great if you can help me to get the InputButtonComponent to work. 

I wrote this code:

`                    <YearPicker
                        InputButtonComponent={()=>{
                            return(
                                <Button
                                    onPress={(val)=>{console.log("how to do this?")}}
                                    title="Click"
                                    color="#841584"/>
                            )}}
                        placeholder={i18n.t('pickYear')}
                        minYear={2019}
                        value={date}
                        onChange={(date)=>{console.log("date", date); }}/>`

how to delegate the onPress of the Button to the Picker itself? I dont get it :/

If you can help me that would be very nice.

**Comment by mgcrea** [comment]
Hey,

Thanks for the kind words,

That's not quite straightforward and might need change but currently the `InputButtonComponent` prop expects a component with an `onFocus` prop, see the provided [InputButtonComponent](https://github.com/mgcrea/react-native-propel-kit/blob/master/packages/button/src/InputButton.tsx) that is used by default.

To customize it further:

1. If it's only style-related you probably want to perform global overrides, see the [docs](https://mgcrea.github.io/react-native-propel-kit/recipes/customizing-styles)

1. If not, you can use an the provided InputButtonComponent a bit like you did:

`InputButtonComponent={({onFocus})=>{ return( <InputButtonComponent onFocus={()=>{console.log("how to do this?"); onFocus();}} title="Click" color="#841584"/> )}}`

1. Or create a component that either return an InputButtonComponent or something with a compatible API.
